backend:
  name: git-gateway        # přihlášení přes Netlify Identity
  branch: main             # větev v GitHubu, kterou používáš
  base_url: https://highendroom.netlify.app

site_url: https://highendroom.netlify.app

media_folder: "public/uploads"    # kam se ukládají obrázky v repozitáři
public_folder: "/uploads"         # jak se k nim přistupuje z webu

collections:
  - name: "products"              # název kolekce
    label: "Produkty"             # název v CMS
    folder: "src/content/products"  # cesta ke složce s produkty
    create: true                  # možnost vytvořit nový produkt
    slug: "{{slug}}"              # slug názvu souboru
    fields:
      - { name: "title", label: "Název", widget: "string" }
      - { name: "brand", label: "Značka", widget: "string" }
      - { name: "category", label: "Kategorie", widget: "select", options: ["obuv","obleceni","batohy","doplnky"] }
      - { name: "subcategory", label: "Podkategorie", widget: "string", required: false }
      - { name: "sizes", label: "Velikosti", widget: "list", required: false, field: {label: "Velikost", name: "size", widget: "string"} }
      - { name: "condition", label: "Stav", widget: "string", required: false }
      - { name: "price", label: "Cena", widget: "number", value_type: "int", min: 0 }
      - { name: "status", label: "Stav produktu", widget: "select", options: ["available", "sold"] }
      - { name: "images", label: "Obrázky", widget: "list", field: {label: "Obrázek", name: "url", widget: "image"} }
      - { name: "tags", label: "Tagy", widget: "list", required: false }
      - { name: "date", label: "Datum", widget: "datetime", required: false }
      - { name: "body", label: "Popis", widget: "markdown", required: false }


